version: 0.2
phases:
  build:
    commands:
      - echo Building JAR file...
      - mvn clean package
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/trip-planner-app.jar
  discard-paths: yes